### ISSUE TITLE
Importing .ply files into disimpy

### ISSUE THREAD

**Issue by tsantini** [kerkelae/disimpy#14]
Dear disimpy creators/collaborators,

I'm trying to simulate a geometry that was originally run in Camino, however, when I try to import the .ply using meshio, I get this geometry:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/26204473/168635956-4ab4854b-9119-4020-b649-3f5977b81514.png">

I then converted the .ply into .stl file using an free online tool, which apparently fixed the problem:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/26204473/168636088-71690fc2-edae-4400-b392-c67976b2eba2.png">

However, when I simulate it, I get something close to free water diffusion, even though I set the structure as periodic.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/26204473/168636357-f3abcf6f-cdec-4ddf-a58d-50825f32e3c6.png">

Please let me know if you have any recommendations or suggestions.

Thanks,
T

**Comment by kerkelae** [comment]
One explanation could be that you are using `init_pos="uniform"` which means that the initial positions of the random walkers are randomly sampled from a unifrom distribution inside the axis-aligned bounding box of the triangles. This means that there are walkers in both intra- and extra-cylindrical spaces. The walkers in the extra-cylindrical space can diffuse far away.

Based on the trajectories plot, this is what seems to happen. You can see that some walkers are restricted to be within the cylinders aligned with the x-axis whereas other walkers are free to diffuse far away. 

In order to simulate diffusion inside the cylinders, you won't be able to use `init_pos="intra"` because the surface is not closed. Instead, you should manually define the initial positions. See [reference](https://disimpy.readthedocs.io/en/latest/modules_and_functions.html#disimpy.substrates.mesh) for details.

Would you be able to share the mesh with me so that I can check if this what is actually happening? If it's not, I'll find the issue and fix it. :)

Hope this helps!

**Comment by tsantini** [comment]
Thanks for your response and for helping the community with this super-fast simulation tool,

My goal was to simulate the intra and extra-cellular signal, mimicking a real signal in the white matter, that's why the  `init_pos="uniform"` is important in my case. 

I thought that when I set `periodic=True`, the structure would repeat itself in all directions, but we only see restriction in x-direction as you observed. It looks like in all other directions, there is nothing restricting the free diffusion. But the structure I'm plotting also looks weird, so maybe there is a problem with how I'm importing the mesh file. 

Here is one of the .ply files I'm using:
https://www.dropbox.com/t/Oo5ZYKkw2oTIIwUn

Thanks,
Tales

**Comment by kerkelae** [comment]
Thanks for sharing the mesh. I think the issue is the angle from which the trajectories are shown.

I ran a simulation on your mesh with `init_pos="uniform"` and `periodic=True`. Then, when I visualize the results using `utils.show_traj(traj_file)`, I get
![default_view](https://user-images.githubusercontent.com/15076450/170489701-bbd50414-bf35-4370-b3f5-df3ae02166e5.png)

This looks like the walkers are diffusing freely. However, If I change the "camera position", I can see that the walkers are in fact diffusing in the extra-cylindrical space:
![different_angle](https://user-images.githubusercontent.com/15076450/170490219-e0acf580-ccc8-4df9-8362-7f0ab45f93d0.png)
The above figure was generated with the code below. Can you try this and let me know if it solves your problem?
```python
trajectories = np.loadtxt(traj_file)
trajectories = trajectories.reshape(
    (trajectories.shape[0], int(trajectories.shape[1] / 3), 3)
)

fig = plt.figure()
ax = fig.add_subplot(111, projection="3d")
for i in range(trajectories.shape[1]):
    ax.plot(
        trajectories[:, i, 0], trajectories[:, i, 1], trajectories[:, i, 2], alpha=0.5,
    )
ax.set_xlabel("x")
ax.set_ylabel("y")
ax.set_zlabel("z")
ax.ticklabel_format(style="sci", scilimits=(0, 0))
ax.view_init(0, 0)  # change the viewing angle
fig.tight_layout()
plt.show()
```

**Comment by tsantini** [comment]
Thanks, that looks beautiful. Would you mind sharing how you read the .ply files as well? I'm still not able to replicate your results.

**Comment by tsantini** [comment]
Thanks, I could replicate your results using the STL file you converted, but I couldn't convert it by myself. Using [meshlab](https://www.meshlab.net/#download), when I load to .ply file and save it as STL, I still have the same problem as before. Do you do something else before exporting it to STL using Meshlab? [Here](https://www.dropbox.com/t/TxZtXYz0gkn3wcPJ) is my converted file.

**Comment by kerkelae** [comment]
Looks like your stl file is identical to the original ply file and my stl file except that it is 10x smaller. I ran the same simulation on your stl file and the results looked good. In order to see the structure in the trajectories plot, it helps to increase the figure size and decrease the line width:

```python
fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection="3d")
for i in range(trajectories.shape[1]):
    ax.plot(
        trajectories[:, i, 0],
        trajectories[:, i, 1],
        trajectories[:, i, 2],
        lw=.1,
    )
ax.set_xlabel("x")
ax.set_ylabel("y")
ax.set_zlabel("z")
ax.ticklabel_format(style="sci", scilimits=(0, 0))
ax.view_init(0, 0)
fig.tight_layout()
fig.savefig("paths.png", dpi=500)
plt.show()
```

![download](https://user-images.githubusercontent.com/15076450/171163902-8c403d42-066c-4ae9-86ae-141bd5345414.png)

Diffusion is free along the x-axis so if your gradient encodes diffusion along that direction, the signal decay curve will be identical to free diffusion. Diffusion in the extra-cylindrical along y and z axes is hindered (i.e., appears like free diffusion with a low apparent diffusion coefficient).

Hope this helps!
